-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 402,
  ["line_length"] = 12,
  ["lines_per_file"] = 6,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, 140 / 64},
  ["sprite_count"] = 64,
  ["width"] = 174,
}
