-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 687,
  ["line_length"] = 1,
  ["lines_per_file"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {7 / 64, 35.5 / 64},
  ["sprite_count"] = 4,
  ["width"] = 810,
}
