-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 368,
  ["line_length"] = 8,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {119 / 64, -117 / 64},
  ["sprite_count"] = 64,
  ["width"] = 466,
}
