-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 116,
  ["line_length"] = 1,
  ["lines_per_file"] = 1,
  ["scale"] = 0.5,
  ["shift"] = {-20 / 64, -209 / 64},
  ["sprite_count"] = 1,
  ["width"] = 170,
}
