-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 520,
  ["line_length"] = 13,
  ["lines_per_file"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {-13 / 64, -215 / 64},
  ["sprite_count"] = 64,
  ["width"] = 174,
}
